apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-payments
  template:
    metadata:
      labels:
        app: ticketing-payments
    spec:
      containers:
        - name: ticketing-payments
          image: kenchinufinity0225/ticketing-payments
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payments-srv
spec:
  selector:
    app: ticketing-payments
  ports:
    - name: ticketing-payments
      protocol: TCP
      port: 3000
      targetPort: 3000
